# Generated by Django 3.0 on 2020-02-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200218_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
