# Generated by Django 3.0 on 2020-02-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200218_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slave',
            options={'verbose_name': 'Раб', 'verbose_name_plural': 'Раби'},
        ),
    ]
