# Generated by Django 3.0 on 2020-02-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='ContactUs',
        ),
    ]
