# Generated by Django 3.0 on 2020-02-18 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200218_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я")),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
            ],
        ),
    ]
