# Generated by Django 3.0 on 2020-02-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_contactusa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='ContactUSA',
        ),
    ]
